Repository eclipse-edc/docs, pull requests merged in 2024-06, with the labels that each got.

#156 fix: resolve 404
  docs/_sidebar.md
Labels: bug

#159 docs: remove checkstyle config
  developer/contributing/save_actions_screenshot.png
  developer/contributing/styleguide.md
  resources/edc-checkstyle-config.xml
  resources/edc-codestyle.editorconfig
  resources/edc-codestyle.xml
  resources/suppressions.xml
Labels: documentation

#160 chore: fix anchor scroll
  docs/index.html
Labels: enhancement
