Repository eclipse-edc/docs, pull requests merged in 2024-05, with the labels that each got.

#146 chore: remove unexisting extensions from know friends
  KNOWN_FRIENDS.md
Labels: enhancement

#148 docs: add addendum re API versioning
  developer/decision-records/2024-05-20-api-versioning-2/README.md
Labels: documentation

#151 feat: adds a Maturity Level and Deprecation Policy Decision Record
  developer/decision-records/2024-05-27-maturity-levels-deprecation-policy/README.md
  developer/decision-records/README.md
Labels: documentation, enhancement
